### ISSUE TITLE
Experiment 1: Random access vs Parquet

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance-research#2]
This is essentially a replication and expansion on the experiment done in “[An Empirical Evaluation of Columnar Formats](https://arxiv.org/abs/2304.05028)”.

Lance is fast at random access because we can slice IOs to read only the required portion of vectors. We’ll compare performance against Parquet.

Dataset: use the Laion-400.

## Variations

* Parquet is sensitive to the row group size, so vary that. See the “Empirical evaluation of columnar formats” paper for values they used.
* Consider warm (file already opened, metadata cached) versus cold (include time to open files)
* Selecting scalar columns, vector columns, and images. This is essentially varying the row size of the projection.
* Local filesystem versus object storage (S3)

## Measurements
* Read latency
* Number of IO calls and total bytes read
  * This is easy to get in Lance by using tracing and counting the number of “get_range” spans and summing the ranges to get the bytes read. We can hook up tracing to the parquet crate and do the same thing for Parquet.

## To-do

* [ ] Bring Laion-400 dataset into S3 bucket
* [ ] Create a Lance and Parquet version of dataset, that includes the images and vectors as columns
* [ ] Create a benchmark program (should go in this repo under `introductory/experiments`)
* [ ] Make measurements
