### ISSUE TITLE
Experiment 2: Scanning vs Parquet and TFRecord

### ISSUE THREAD

**Issue by wjones127** [lancedb/lance-research#4]
TODO: figure out exact experiment. Which design choice(s) make Lance a better choice than Parquet or TFRecord? What experiment would demonstrate that?

* Late materialization of large columns?
  * experiment: Add switch to turn off late materialization, compare query times, num IOs, bytes read
* Deserialization overhead for vector columns?
  * experiment: benchmark time to take buffer and turn into in-memory format. (Lance vs Parquet vs ORC vs TFRecord)
  * Also better for full scan of large binary blobs
* Column projection (better than TFRecord)
* Deeply nested (struct) filtering / projection 
* Related to future work: how much does lack of encoding hit us ATM.
* Should we incorporate stats and scalar indexes?
   * Let's do one small experiment on this

## Formats to compare to

* Parquet
* TFRecord

## Experiment 2a: Late materialization

Demonstrate effect of late materialization in Lance queries.

### Parameters

* Late materialization turned on in Lance
* Filter selectivity, filter sparseness
* Which columns are projected after filter (scalar, vector, image)

### Measurements

* Time to read
* Number of IO calls
* Total bytes read

### TODO

* [x] Add switch in Lance to turn off late materialization
* [ ] Get dataset and choose filter
* [ ] Build bench for Lance
* [ ] Build bench for Parquet
   * This requires finding a way to do late materialization with Parquet. It's probably worth it to be able to do this just to get num IO calls + total bytes read.
* [ ] Collect data

## Experiment 2b: Vector and blob encoding

Demonstrate Lance's advantages storing and decoding vector and image data. We are comparing reading into Arrow memory.

Setup will be writing files into memory that are just one column. By putting into memory we reduce the IO cost. By doing one column at a time we reduce influence of parallelism and column skipping. We also want to reduce measurement of metadata overhead.

### Parameters

* Type: embedding vector vs blob encoding

### Measurements

* On-disk size of columns
* Time to decode from memory

### TODO

* [ ] Make sure Lance supports in-memory
* [ ] Write datagen scripts:
    * [ ] Parquet
    * [ ] Lance
    * [ ] TFRecord
* [ ] Build bench scripts:
    * [ ] PyArrow
    * [ ] Lance
    * [ ] TFRecord
* [ ] Collect data
